const theme = require('../../theme')
module.exports = {
  'terminal.background': theme.bg,
  'terminal.foreground': theme.bg_lighter,
  'terminalCursor.background': theme.green,
  'terminalCursor.foreground': theme.green,
  'terminal.ansiBlack': '#374E73',
  'terminal.ansiBlue': theme.blue,
  'terminal.ansiCyan': theme.accent_lighter,
  'terminal.ansiGreen': theme.green,
  'terminal.ansiMagenta': theme.purple,
  'terminal.ansiRed': theme.rouge,
  'terminal.ansiWhite': theme.rouge_lighter,
  'terminal.ansiYellow': theme.grapple,
  'terminal.ansiBrightBlack': '#3F5A85',
  'terminal.ansiBrightBlue': theme.blue_light,
  'terminal.ansiBrightCyan': theme.accent_lighter,
  'terminal.ansiBrightGreen': theme.green_light,
  'terminal.ansiBrightMagenta': theme.purple_light,
  'terminal.ansiBrightRed': theme.rouge_light,
  'terminal.ansiBrightWhite': theme.rouge_lightest,
  'terminal.ansiBrightYellow': theme.grapple_light,
}
