module.exports = {
  'terminal.background': '#fff',
  'terminal.foreground': '#b8bcc6',
  'terminalCursor.background': '#ADB9A4',
  'terminalCursor.foreground': '#ADB9A4',
  'terminal.ansiBlack': '#374E73',
  'terminal.ansiBlue': '#6e94b9',
  'terminal.ansiCyan': '#8ab6c1',
  'terminal.ansiGreen': '#ADB9A4',
  'terminal.ansiMagenta': '#b18bb1',
  'terminal.ansiRed': '#c6797e',
  'terminal.ansiWhite': '#e3e4e8',
  'terminal.ansiYellow': '#ece7ac',
  'terminal.ansiBrightBlack': '#3F5A85',
  'terminal.ansiBrightBlue': '#98b3cd',
  'terminal.ansiBrightCyan': '#abcbd3',
  'terminal.ansiBrightGreen': '#bec8b7',
  'terminal.ansiBrightMagenta': '#ccb3cc',
  'terminal.ansiBrightRed': '#d19498',
  'terminal.ansiBrightWhite': '#fff',
  'terminal.ansiBrightYellow': '#F2EFC7',
}
